# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: liquidity.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'liquidity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fliquidity.proto\x12\x18market_analyst.liquidity\"\"\n\x10LiquidityRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\"W\n\x10LiquiditySummary\x12\x13\n\x0b\x61sset_class\x18\x01 \x01(\t\x12\x17\n\x0fliquidity_score\x18\x02 \x01(\x01\x12\x15\n\rmarket_regime\x18\x03 \x01(\t2\x8a\x01\n\x16MacroLiquidityAnalyzer\x12p\n\x14SubscribeToLiquidity\x12*.market_analyst.liquidity.LiquidityRequest\x1a*.market_analyst.liquidity.LiquiditySummary0\x01\x42\x1a\n\x16\x63om.marketanalyst.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'liquidity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.marketanalyst.grpcP\001'
  _globals['_LIQUIDITYREQUEST']._serialized_start=45
  _globals['_LIQUIDITYREQUEST']._serialized_end=79
  _globals['_LIQUIDITYSUMMARY']._serialized_start=81
  _globals['_LIQUIDITYSUMMARY']._serialized_end=168
  _globals['_MACROLIQUIDITYANALYZER']._serialized_start=171
  _globals['_MACROLIQUIDITYANALYZER']._serialized_end=309
# @@protoc_insertion_point(module_scope)
