# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: macro_sentiment.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'macro_sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15macro_sentiment.proto\x12\x1emarket_analyst.macro_sentiment\"\x0e\n\x0cMacroRequest\"T\n\x0bMacroReport\x12\x15\n\rmarket_stance\x18\x01 \x01(\t\x12\x17\n\x0fsummary_bullets\x18\x02 \x03(\t\x12\x15\n\rsources_cited\x18\x03 \x03(\t2\x85\x01\n\x16MacroSentimentAnalyzer\x12k\n\x0eGetGlobalMacro\x12,.market_analyst.macro_sentiment.MacroRequest\x1a+.market_analyst.macro_sentiment.MacroReportB\x1a\n\x16\x63om.marketanalyst.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'macro_sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.marketanalyst.grpcP\001'
  _globals['_MACROREQUEST']._serialized_start=57
  _globals['_MACROREQUEST']._serialized_end=71
  _globals['_MACROREPORT']._serialized_start=73
  _globals['_MACROREPORT']._serialized_end=157
  _globals['_MACROSENTIMENTANALYZER']._serialized_start=160
  _globals['_MACROSENTIMENTANALYZER']._serialized_end=293
# @@protoc_insertion_point(module_scope)
