# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import macro_sentiment_pb2 as macro__sentiment__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in macro_sentiment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MacroSentimentAnalyzerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGlobalMacro = channel.unary_unary(
                '/market_analyst.macro_sentiment.MacroSentimentAnalyzer/GetGlobalMacro',
                request_serializer=macro__sentiment__pb2.MacroRequest.SerializeToString,
                response_deserializer=macro__sentiment__pb2.MacroReport.FromString,
                _registered_method=True)


class MacroSentimentAnalyzerServicer:
    """Missing associated documentation comment in .proto file."""

    def GetGlobalMacro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MacroSentimentAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGlobalMacro': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalMacro,
                    request_deserializer=macro__sentiment__pb2.MacroRequest.FromString,
                    response_serializer=macro__sentiment__pb2.MacroReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market_analyst.macro_sentiment.MacroSentimentAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('market_analyst.macro_sentiment.MacroSentimentAnalyzer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MacroSentimentAnalyzer:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGlobalMacro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market_analyst.macro_sentiment.MacroSentimentAnalyzer/GetGlobalMacro',
            macro__sentiment__pb2.MacroRequest.SerializeToString,
            macro__sentiment__pb2.MacroReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
