# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sector_rotation_pb2 as sector__rotation__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sector_rotation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SectorRotationMonitorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeToSector = channel.unary_stream(
                '/market_analyst.rotation.SectorRotationMonitor/SubscribeToSector',
                request_serializer=sector__rotation__pb2.SectorSubscription.SerializeToString,
                response_deserializer=sector__rotation__pb2.RotationAlert.FromString,
                _registered_method=True)
        self.GetMidTermClusters = channel.unary_unary(
                '/market_analyst.rotation.SectorRotationMonitor/GetMidTermClusters',
                request_serializer=sector__rotation__pb2.EmptyRequest.SerializeToString,
                response_deserializer=sector__rotation__pb2.ClusterOverviewResponse.FromString,
                _registered_method=True)
        self.GetRelativeValue = channel.unary_unary(
                '/market_analyst.rotation.SectorRotationMonitor/GetRelativeValue',
                request_serializer=sector__rotation__pb2.TickerRequest.SerializeToString,
                response_deserializer=sector__rotation__pb2.RelativeValueResponse.FromString,
                _registered_method=True)


class SectorRotationMonitorServicer:
    """Missing associated documentation comment in .proto file."""

    def SubscribeToSector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMidTermClusters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelativeValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SectorRotationMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeToSector': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToSector,
                    request_deserializer=sector__rotation__pb2.SectorSubscription.FromString,
                    response_serializer=sector__rotation__pb2.RotationAlert.SerializeToString,
            ),
            'GetMidTermClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMidTermClusters,
                    request_deserializer=sector__rotation__pb2.EmptyRequest.FromString,
                    response_serializer=sector__rotation__pb2.ClusterOverviewResponse.SerializeToString,
            ),
            'GetRelativeValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelativeValue,
                    request_deserializer=sector__rotation__pb2.TickerRequest.FromString,
                    response_serializer=sector__rotation__pb2.RelativeValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market_analyst.rotation.SectorRotationMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('market_analyst.rotation.SectorRotationMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SectorRotationMonitor:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeToSector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/market_analyst.rotation.SectorRotationMonitor/SubscribeToSector',
            sector__rotation__pb2.SectorSubscription.SerializeToString,
            sector__rotation__pb2.RotationAlert.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMidTermClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market_analyst.rotation.SectorRotationMonitor/GetMidTermClusters',
            sector__rotation__pb2.EmptyRequest.SerializeToString,
            sector__rotation__pb2.ClusterOverviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelativeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market_analyst.rotation.SectorRotationMonitor/GetRelativeValue',
            sector__rotation__pb2.TickerRequest.SerializeToString,
            sector__rotation__pb2.RelativeValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
