# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sector_rotation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sector_rotation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15sector_rotation.proto\x12\x17market_analyst.rotation\"O\n\x0b\x43lusterPeer\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\x12\x1a\n\x12performance_spread\x18\x03 \x01(\x01\"\x80\x02\n\x15RelativeValueResponse\x12\x15\n\rtarget_ticker\x18\x01 \x01(\t\x12\x13\n\x0btarget_name\x18\x02 \x01(\t\x12\x12\n\ncluster_id\x18\x03 \x01(\x05\x12\x12\n\ntheme_name\x18\x04 \x01(\t\x12\x1e\n\x16\x63luster_average_return\x18\x05 \x01(\x01\x12;\n\routperformers\x18\x06 \x03(\x0b\x32$.market_analyst.rotation.ClusterPeer\x12\x36\n\x08laggards\x18\x07 \x03(\x0b\x32$.market_analyst.rotation.ClusterPeer\"\x97\x01\n\x0e\x43lusterSummary\x12\x12\n\ncluster_id\x18\x01 \x01(\x05\x12\x12\n\ntheme_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x19\n\x11\x63onstituent_count\x18\x04 \x01(\x05\x12\x18\n\x10\x61verage_momentum\x18\x05 \x01(\x01\x12\x13\n\x0btop_tickers\x18\x06 \x03(\t\"T\n\x17\x43lusterOverviewResponse\x12\x39\n\x08\x63lusters\x18\x01 \x03(\x0b\x32\'.market_analyst.rotation.ClusterSummary\"\x0e\n\x0c\x45mptyRequest\"\x1f\n\rTickerRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\"+\n\x12SectorSubscription\x12\x15\n\rurgency_level\x18\x01 \x01(\t\":\n\nSectorData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x01\x12\x10\n\x08momentum\x18\x03 \x01(\x01\"X\n\rRotationAlert\x12\x34\n\x07sectors\x18\x01 \x03(\x0b\x32#.market_analyst.rotation.SectorData\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32\xde\x02\n\x15SectorRotationMonitor\x12j\n\x11SubscribeToSector\x12+.market_analyst.rotation.SectorSubscription\x1a&.market_analyst.rotation.RotationAlert0\x01\x12m\n\x12GetMidTermClusters\x12%.market_analyst.rotation.EmptyRequest\x1a\x30.market_analyst.rotation.ClusterOverviewResponse\x12j\n\x10GetRelativeValue\x12&.market_analyst.rotation.TickerRequest\x1a..market_analyst.rotation.RelativeValueResponseB\x1a\n\x16\x63om.marketanalyst.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sector_rotation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.marketanalyst.grpcP\001'
  _globals['_CLUSTERPEER']._serialized_start=50
  _globals['_CLUSTERPEER']._serialized_end=129
  _globals['_RELATIVEVALUERESPONSE']._serialized_start=132
  _globals['_RELATIVEVALUERESPONSE']._serialized_end=388
  _globals['_CLUSTERSUMMARY']._serialized_start=391
  _globals['_CLUSTERSUMMARY']._serialized_end=542
  _globals['_CLUSTEROVERVIEWRESPONSE']._serialized_start=544
  _globals['_CLUSTEROVERVIEWRESPONSE']._serialized_end=628
  _globals['_EMPTYREQUEST']._serialized_start=630
  _globals['_EMPTYREQUEST']._serialized_end=644
  _globals['_TICKERREQUEST']._serialized_start=646
  _globals['_TICKERREQUEST']._serialized_end=677
  _globals['_SECTORSUBSCRIPTION']._serialized_start=679
  _globals['_SECTORSUBSCRIPTION']._serialized_end=722
  _globals['_SECTORDATA']._serialized_start=724
  _globals['_SECTORDATA']._serialized_end=782
  _globals['_ROTATIONALERT']._serialized_start=784
  _globals['_ROTATIONALERT']._serialized_end=872
  _globals['_SECTORROTATIONMONITOR']._serialized_start=875
  _globals['_SECTORROTATIONMONITOR']._serialized_end=1225
# @@protoc_insertion_point(module_scope)
