# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: structural_analysis.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'structural_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19structural_analysis.proto\x12\x19market_analyst.structural\"~\n\x0f\x41nalysisRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x1b\n\x13time_horizon_months\x18\x02 \x01(\x05\x12\x1c\n\x14include_supply_chain\x18\x03 \x01(\x08\x12 \n\x18include_competitor_intel\x18\x04 \x01(\x08\"R\n\x0eKeyOpportunity\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x18\n\x10\x63onviction_score\x18\x02 \x01(\x01\x12\x11\n\ttimeframe\x18\x03 \x01(\t\"Q\n\nRiskFactor\x12\x18\n\x10risk_description\x18\x01 \x01(\t\x12\x16\n\x0eseverity_score\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"\xee\x02\n\x0e\x41nalysisReport\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x19\n\x11\x65xecutive_summary\x18\x02 \x01(\t\x12\x11\n\tbull_case\x18\x03 \x01(\t\x12\x11\n\tbear_case\x18\x04 \x01(\t\x12\x38\n\tkey_risks\x18\x05 \x03(\x0b\x32%.market_analyst.structural.RiskFactor\x12\x44\n\x11key_opportunities\x18\x06 \x03(\x0b\x32).market_analyst.structural.KeyOpportunity\x12\x15\n\rsources_cited\x18\x07 \x03(\t\x12\x12\n\nhype_index\x18\x08 \x01(\x01\x12\x15\n\rgraham_number\x18\t \x01(\x01\x12\x18\n\x10margin_of_safety\x18\n \x01(\x01\x12\x16\n\x0e\x61ltman_z_score\x18\x0b \x01(\x01\x12\x17\n\x0f\x61ltman_z_status\x18\x0c \x01(\t2\x81\x01\n\x12StructuralAnalyzer\x12k\n\x12GenerateDeepReport\x12*.market_analyst.structural.AnalysisRequest\x1a).market_analyst.structural.AnalysisReportB\x1a\n\x16\x63om.marketanalyst.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'structural_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.marketanalyst.grpcP\001'
  _globals['_ANALYSISREQUEST']._serialized_start=56
  _globals['_ANALYSISREQUEST']._serialized_end=182
  _globals['_KEYOPPORTUNITY']._serialized_start=184
  _globals['_KEYOPPORTUNITY']._serialized_end=266
  _globals['_RISKFACTOR']._serialized_start=268
  _globals['_RISKFACTOR']._serialized_end=349
  _globals['_ANALYSISREPORT']._serialized_start=352
  _globals['_ANALYSISREPORT']._serialized_end=718
  _globals['_STRUCTURALANALYZER']._serialized_start=721
  _globals['_STRUCTURALANALYZER']._serialized_end=850
# @@protoc_insertion_point(module_scope)
